name: "\U0001F504 변경요청"
description: "기존 기능의 변경이나 수정을 요청합니다."
labels: ["change-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## 변경 요청
        기존 기능의 동작 변경, 사양 수정, 정책 변경 등을 요청할 때 사용합니다.

  - type: textarea
    id: current-behavior
    attributes:
      label: "현재 동작"
      description: "현재 어떻게 동작하고 있는지 설명하세요."
      placeholder: "예: 장비 목록에서 한 페이지에 10개씩 표시되고 있습니다."
    validations:
      required: true

  - type: textarea
    id: requested-change
    attributes:
      label: "변경 요청 내용"
      description: "어떻게 변경되어야 하는지 구체적으로 설명하세요."
      placeholder: "예: 한 페이지에 50개씩 표시하고, 페이지당 표시 개수를 사용자가 선택할 수 있도록 변경"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "변경 사유"
      description: "왜 이 변경이 필요한지 배경을 설명하세요."
      placeholder: "예: 딜러가 관리하는 장비가 많아 10개씩은 비효율적이라는 피드백"
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "영향 범위"
      description: "이 변경으로 영향 받는 화면, 기능, 사용자 등을 기재하세요."
      value: |
        - **영향 화면**:
        - **영향 기능**:
        - **영향 사용자**:

  - type: dropdown
    id: priority
    attributes:
      label: "우선순위"
      description: "이 변경의 긴급도를 선택하세요."
      options:
        - "낮음 - 다음 릴리스에 포함"
        - "보통 - 가까운 스프린트에 반영"
        - "높음 - 현재 스프린트에 반영 필요"
        - "긴급 - 즉시 반영 필요"

  - type: textarea
    id: notes
    attributes:
      label: "추가 정보"
      description: "스크린샷, 관련 이슈 번호, 참고자료 등을 첨부하세요."
