name: "\U0001F3E2 업무영역 (Epic)"
description: "최상위 업무 범주를 정의합니다."
labels: ["type:업무영역", "status:backlog"]
body:
  - type: markdown
    attributes:
      value: |
        ## 업무영역 등록
        프로젝트의 최상위 업무 범주를 정의합니다.
        하위에 **상세기능**을 Sub-Issue로 연결하세요.

  - type: input
    id: goal
    attributes:
      label: "목표"
      description: "이 업무영역이 달성해야 할 핵심 목표를 한 문장으로 작성하세요."
      placeholder: "예: 딜러 포털의 장비 관리 기능 구축"
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: "범위"
      description: "이 업무영역에 포함되는 기능/모듈 범위를 설명하세요."
      placeholder: |
        - 장비 등록/수정/삭제
        - 장비 상태 모니터링
        - 장비 이력 조회

  - type: textarea
    id: success-criteria
    attributes:
      label: "성공 기준"
      description: "이 업무영역의 완료 조건을 체크리스트로 작성하세요."
      value: |
        - [ ] 기준 1
        - [ ] 기준 2

  - type: textarea
    id: context
    attributes:
      label: "배경 및 참고사항"
      description: "관련 문서, 의사결정 배경, 제약사항 등을 기재하세요."
      placeholder: "관련 문서 링크, 비즈니스 배경 등"
