name: "\U0001F4AC 요청사항"
description: "새 기능, 기존 기능 변경, 개선 사항을 요청합니다."
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 요청사항 등록
        새로운 기능 추가, 기존 기능 변경, 개선 사항 등을 요청할 때 사용합니다.

  - type: dropdown
    id: request-type
    attributes:
      label: "요청 유형"
      description: "요청의 유형을 선택하세요."
      options:
        - "신규 기능"
        - "기존 기능 변경"
        - "개선/최적화"
    validations:
      required: true

  - type: textarea
    id: current-situation
    attributes:
      label: "현재 상황"
      description: "현재 어떤 상황이고 왜 이 요청이 필요한지 설명하세요."
      placeholder: "예: 장비 목록에서 원하는 장비를 찾으려면 전체를 스크롤해야 합니다."
    validations:
      required: true

  - type: textarea
    id: requested-content
    attributes:
      label: "요청 내용"
      description: "원하는 결과를 구체적으로 설명하세요."
      placeholder: "예: 장비 목록 상단에 이름/모델/시리얼 번호로 검색할 수 있는 검색바 추가"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "대안"
      description: "고려해본 다른 방법이 있다면 기재하세요."

  - type: dropdown
    id: priority
    attributes:
      label: "우선순위"
      description: "이 요청의 중요도를 선택하세요."
      options:
        - "낮음 - 있으면 좋은 수준"
        - "보통 - 업무에 도움이 됨"
        - "높음 - 업무에 필요함"
        - "긴급 - 즉시 필요함"

  - type: textarea
    id: context
    attributes:
      label: "추가 정보"
      description: "스크린샷, 관련 이슈 번호, 참고자료 등을 첨부하세요."
